//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklist
    {
        public int checklist_id { get; set; }
        public string checklist_name { get; set; }
        public string checklist_description { get; set; }
        public string trip_name { get; set; }
        public string trip_description { get; set; }
        public string trip_date { get; set; }
        public string checklist_summary { get; set; }
        public int user_id { get; set; }
    
        public virtual app_users app_users { get; set; }
    }
}
